package no.obos.util.servicebuilder.mq;

import org.junit.Test;

import static org.assertj.core.api.Assertions.assertThat;

public class ActiveMqListenerLoggingTest {

    @Test
    public void handleNull() {
        assertThat(ActiveMqListener.truncateMessageForLogging(null)).isEqualTo(null);
    }

    @Test
    public void logNormalLengthMessage() {
        String msg = "{\"mottakerId\":13136040,\"message\":\"Hei Adam! Eva ber om å bli lagt til som beboer"
                + " i Lade Alle Hjem Boligsameie. Gå til Min bolig på https://vibbo.no/xxxx for å godta forespørselen.\",\"from\":\"Vibbo\",\"to\":\"99999999\"}";

        assertThat(ActiveMqListener.truncateMessageForLogging(msg)).isEqualTo(msg);
    }
    @Test
    public void logLongMessageWithDataObject() {
        String msg = "{\"dated\":[2023,8,21],\"scanned\":null,\"userId\":null,\"type\":\"Inngående\",\"status\":null,\"projectName\":null,\"reference\":null,"
                + "\"title\":\"Kontoutskrift Santander høyrentekonto 280575114.pdf\",\"archivekeyNo\":null,\"archivekeyName\":null,\"author\":null,"
                + "\"receiver\":null,\"involved\":null,\"kundenummer\":732646,\"objektnummer\":null,\"selskapsnummer\":null,\"month\":null,\"year\":null,"
                + "\"amount\":null,\"caseworker\":null,\"category1\":\"Forkjøp\",\"category2\":\"Finansiering\",\"owner\":\"OBOS konsernet\","
                + "\"classification\":\"Beskyttet\",\"storageRoutine\":\"LS32\",\"template\":null,\"comment\":null,"
                + "\"files\":[{\"name\":\"Kontoutskrift Santander høyrentekonto 280575114.pdf\","
                + "\"data\":\"JVBERi0xLjQNCiX15Pb8DQoNCjkgMCBvYmoNCjw8DQovVHlwZSAvWE9iamVjdA0KL1N1YnR5cGUgL0ltYWdlDQovTmFtZSAvSTENCi9XaWR0aCAyMzI2DQovSGVpZ2"
                + "h0IDEwNTQNCi9CaXRzUGVyQ29tcG9uZW50IDgNCi9Db2xvclNwYWNlIC9EZXZpY2VSR0INCi9MZW5ndGggMTQwMzY2IC9GaWx0ZXIgWyAvRmxhdGVEZWNvZGUgXSA+Pg0Kc3RyZWF"
                + "tDQp4nOzdXXYTV9owbEv4GJIBdJIJpOn1nSc0A0gnA+iVMIE8MIGGZABN088AoHP+dMhz/K6GZALA6gEk6aP3iyzJdoAYbKn0VtX+qS3bkn/BJrmupWWELEulUu36ue+97z2bAQAAA"
                + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
                + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
                + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
                + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
                + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
                + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
                + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
                + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
                + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
                + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
                + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
                + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
                + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
                + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
                + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
                + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
                + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
                + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
                + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
                + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
                + "AAPzaTGbT2Wxa1feqWVVN8uNVVbX/TOJvG9NZFf6kfjw8GB/ZXzXrflulH1XxF+H+pIov3tzS63eat5jmZ1azXU9+teJiN+8VV0hjp4q/mk7nPs8srKuqfXJVPBJWRbc+ij8Kf1DlVZ9"
                + "+UcX3nab1c5baJdhJd6bNh1u2UK/lqzklcTOOG/nOgU/Nnzu0gmO9Z/FXk6qKm9bcS7UPTqpiO59vSXmx87Pnf91tac3WM8nPKZ65q5Xt/j7PfqPbazqdpZZX5UbUroQqrsPYjHZvnt"
                + "PiK557ML1cUqzG7m6VvvhJtfe3s9woZnP7z/2Xv9q9FR1P+za7ttUDNsW8rtrPfD5baF49+Xvp9jnhd8vX7zkwTRvZnga135Pn/7tz1p9umn7G3U633yi2n27/034d7Z3JrNyk508X0s"
                + "6t+7Dbe55bzf9h/t2u04vqxA1njzf6+3q18ilMOtM7zCp6hcJGls6vJmn76s7N5hb4HJw1nZoqnAyk+/HRrnG0DaVpYs0qmlTF/rM7+cxPneXz8LjW8sNZ2eym8b/FMw59vJuVe4zW"
                + "0vOrgxz+ONt+rmmVN4+TvOurNU1LmPa3h3jyrNs1Hv84foTz3vaZ4UqnOzqf5SnEfjuiQ33H01nRjgAAAI5luh";

        String expectedLoggedMessage = "{\"dated\":[2023,8,21],\"scanned\":null,\"userId\":null,\"type\":\"Inngående\",\"status\":null,\"projectName\":null,"
                + "\"reference\":null,\"title\":\"Kontoutskrift Santander høyrentekonto 280575114.pdf\",\"archivekeyNo\":null,\"archivekeyName\":null,"
                + "\"author\":null,\"receiver\":null,\"involved\":null,\"kundenummer\":732646,\"objektnummer\":null,\"selskapsnummer\":null,\"month\":null,"
                + "\"year\":null,\"amount\":null,\"caseworker\":null,\"category1\":\"Forkjøp\",\"category2\":\"Finansiering\","
                + "\"owner\":\"OBOS konsernet\",\"classification\":\"Beskyttet\",\"storageRoutine\":\"LS32\",\"template\":null,\"comment\":null,"
                + "\"files\":[{\"name\":\"Kontoutskrift Santander høyrentekonto 280575114.pdf\",\"data\":\"...\"}";

        assertThat(ActiveMqListener.truncateMessageForLogging(msg)).isEqualTo(expectedLoggedMessage);
    }

    @Test
    public void logLongMessageWithoutDataObject() {
        String msg = "{\"dated\":[2023,8,21],\"scanned\":null,\"userId\":null,\"type\":\"Inngående\",\"status\":null,\"projectName\":null,\"reference\":null,"
                + "\"title\":\"Kontoutskrift Santander høyrentekonto 280575114.pdf\",\"archivekeyNo\":null,\"archivekeyName\":null,\"author\":null,"
                + "\"receiver\":null,\"involved\":null,\"kundenummer\":732646,\"objektnummer\":null,\"selskapsnummer\":null,\"month\":null,\"year\":null,"
                + "\"amount\":null,\"caseworker\":null,\"category1\":\"Forkjøp\",\"category2\":\"Finansiering\",\"owner\":\"OBOS konsernet\","
                + "\"classification\":\"Beskyttet\",\"storageRoutine\":\"LS32\",\"template\":null,\"comment\":null,"
                + "\"files\":[{\"name\":\"Kontoutskrift Santander høyrentekonto 280575114.pdf\","
                + "JVBERi0xLjQNCiX15Pb8DQoNCjkgMCBvYmoNCjw8DQovVHlwZSAvWE9iamVjdA0KL1N1YnR5cGUgL0ltYWdlDQovTmFtZSAvSTENCi9XaWR0aCAyMzI2DQovSGVpZ2"
                + "h0IDEwNTQNCi9CaXRzUGVyQ29tcG9uZW50IDgNCi9Db2xvclNwYWNlIC9EZXZpY2VSR0INCi9MZW5ndGggMTQwMzY2IC9GaWx0ZXIgWyAvRmxhdGVEZWNvZGUgXSA+Pg0Kc3RyZWF"
                + "tDQp4nOzdXXYTV9owbEv4GJIBdJIJpOn1nSc0A0gnA+iVMIE8MIGGZABN088AoHP+dMhz/K6GZALA6gEk6aP3iyzJdoAYbKn0VtX+qS3bkn/BJrmupWWELEulUu36ue+97z2bAQAAA"
                + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
                + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
                + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
                + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
                + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
                + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
                + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
                + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
                + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
                + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
                + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
                + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
                + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
                + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
                + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
                + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
                + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
                + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
                + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
                + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
                + "AAPzaTGbT2Wxa1feqWVVN8uNVVbX/TOJvG9NZFf6kfjw8GB/ZXzXrflulH1XxF+H+pIov3tzS63eat5jmZ1azXU9+teJiN+8VV0hjp4q/mk7nPs8srKuqfXJVPBJWRbc+ij8Kf1DlVZ9"
                + "+UcX3nab1c5baJdhJd6bNh1u2UK/lqzklcTOOG/nOgU/Nnzu0gmO9Z/FXk6qKm9bcS7UPTqpiO59vSXmx87Pnf91tac3WM8nPKZ65q5Xt/j7PfqPbazqdpZZX5UbUroQqrsPYjHZvnt"
                + "PiK557ML1cUqzG7m6VvvhJtfe3s9woZnP7z/2Xv9q9FR1P+za7ttUDNsW8rtrPfD5baF49+Xvp9jnhd8vX7zkwTRvZnga135Pn/7tz1p9umn7G3U633yi2n27/034d7Z3JrNyk508X0s"
                + "6t+7Dbe55bzf9h/t2u04vqxA1njzf6+3q18ilMOtM7zCp6hcJGls6vJmn76s7N5hb4HJw1nZoqnAyk+/HRrnG0DaVpYs0qmlTF/rM7+cxPneXz8LjW8sNZ2eym8b/FMw59vJuVe4zW"
                + "0vOrgxz+ONt+rmmVN4+TvOurNU1LmPa3h3jyrNs1Hv84foTz3vaZ4UqnOzqf5SnEfjuiQ33H01nRjgAAAI5luh";
        assertThat(ActiveMqListener.truncateMessageForLogging(msg).length()).isEqualTo(ActiveMqListener.MAX_LENGTH_PER_MESSAGE);
    }
}